---

# Specific install tasks for Debian family

- name: 'INSTALL | APT | Install packages'
  become: True
  apt:
    name: "{{ item.name }}"
    update_cache: True
    cache_valid_time: "{{ rsync_server_repository_cache_valid_time }}"
    state: "{{ item.state | default('present') }}"
  notify: 'HANDLER | Restart Rsync'
  loop: "{{ rsync_server_packages }}"
