---

# Main tasks file for rsync-server role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::rsync-server'
    - 'role::rsync-server::config'
    - 'role::rsync-server::init'
    - 'role::rsync-server::install'


- name: 'INSTALL | Manage os family installation tasks'
  include_tasks: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::rsync-server'
    - 'role::rsync-server::install'


- name: 'INSTALL | Manage configuration'
  include_tasks: "{{ role_path }}/tasks/manage_config.yml"
  tags:
    - 'role::rsync-server'
    - 'role::rsync-server::config'


- name: 'INSTALL | Manage service'
  include_tasks: "{{ role_path }}/tasks/manage_service.yml"
  when: 'rsync_server_service | bool'
  tags:
    - 'role::rsync-server'
    - 'role::rsync-server::install'
