---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "rsync-server-docker-centos7"
    groups:
      - 'centos'
    image: 'jrei/systemd-centos:7'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "rsync-server-docker-centos8"
    groups:
      - 'centos'
    image: 'jrei/systemd-centos:8'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "rsync-server-docker-debian9"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:9'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "rsync-server-docker-debian10"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:10'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "rsync-server-docker-ubuntu18"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:18.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "rsync-server-docker-ubuntu20"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:20.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: 'ansible'
  inventory:
    group_vars:
      all:
        rsync_server_config_main:
          global: |
            log file = /var/log/rsync/rsyncd.log
            uid = rsync
            gid = rsync
          modules:
            - name: 'backup_01'
              config: |
                path = /data/backup_01
                comment = Backup testing 01
        # Unable to test properly systemd services
        rsync_server_service: null
        rsync_users:
          - name: 'foo'
            password: 'bar'
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  options:
    sudo: True
